[package]
name = "log-archive-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
rayon = "1.10.0"
regex = "1.10.4"
tokio = { version = "1.37.0", features = ["full"] }
zip = "1.1.3"
